#!/bin/bash -i
GIT_REPO_PATH="$1"
FETCH="$2"

# Verifica se as configurações estão iniciadas
git-init-config


if [[ "$FETCH" != "false" ]]; then
	git-cmd fetch "-v $TIDEXA_GIT_GLOBAL_NAMESPACE" "$GIT_REPO_PATH"
fi
git-cmd diff "--shortstat origin/master $TIDEXA_GIT_GLOBAL_NAMESPACE/master" "$GIT_REPO_PATH"
