#!/bin/bash
# Verifica se as configurações estão iniciadas
git-init-config

TEST=$(echo "$TIDEXA_GIT_GLOBAL_NAMESPACE")
if [[ -z "$TEST" ]]; then
	echo "Chame esse script colocando . antes para carregar as variáveis de ambiente. Exemplo: . git-clone URL"
	exit
fi
GIT_REPO_PATH="$1"
git clone -v "$GIT_REPO_PATH"
REPO_NAME=$(basename "$GIT_REPO_PATH")
DIR_NAME="${REPO_NAME%.*}"
cd $DIR_NAME
git remote add $TIDEXA_GIT_GLOBAL_NAMESPACE git@$TIDEXA_GIT_URL:$TIDEXA_GIT_GLOBAL_NAMESPACE/$REPO_NAME
cd ..