#!/bin/bash
GIT_REPO_PATH="$1"
CLEAR="$2"
MESSAGE="$3"
OUTPUT=$(git-cmd test-commit "" "$GIT_REPO_PATH" "$CLEAR")
STATUS=$?
if [[ "$STATUS" == "0" ]]; then
	if [[ -z "$MESSAGE" ]]; then
		echo "Mensagem do commit"
		read "MESSAGE"
	fi
	git-cmd commit "-m $MESSAGE" "$GIT_REPO_PATH" "$CLEAR"
else
	echo "$OUTPUT"
	exit "$STATUS"
fi
