#!/bin/bash -i
# Verifica se as configurações estão iniciadas
git-init-config

GIT_REMOTE_NAMESPACE_ALIAS="$1"
GIT_REMOTE_NAMESPACE="$2"
GIT_REPO_URL="$3"

REPO_NAME=$(basename "$GIT_REPO_URL")
GIT_REPO_PATH="${REPO_NAME%.*}"
git-cmd remote "add $GIT_REMOTE_NAMESPACE_ALIAS git@$TIDEXA_GIT_URL:$GIT_REMOTE_NAMESPACE/$REPO_NAME" "$GIT_REPO_PATH"
