#!/bin/bash
GIT_REPO_PATH="$1"
git-add "$GIT_REPO_PATH"
git-cmd-commit "$GIT_REPO_PATH" "false"
git-global-push "$GIT_REPO_PATH" "false"
if [[ $? -eq 0 ]]; then
	git-push "$GIT_REPO_PATH" "" "false"
fi
