#!/bin/bash -i
# Verifica se as configurações estão iniciadas
git-init-config

GIT_REPO_URL="$1"
GIT_GLOBAL_NAMESPACE="$2"

if [[ -z "$GIT_GLOBAL_NAMESPACE" ]]; then
	GIT_GLOBAL_NAMESPACE="$TIDEXA_GIT_GLOBAL_NAMESPACE"
fi

git clone -v "$GIT_REPO_URL"
git-global-add "$GIT_GLOBAL_NAMESPACE" "$GIT_REPO_URL"
