#!/bin/bash
# CHANGE indica se está trocando ou criando/verificando
CHANGE="$1"

# Importação
. utils.sh

changeGitProperty() {
	local question="$1"
	local gitProperty="$2"
	GIT_CMD="git config --global $gitProperty"
	if [[ "$CHANGE" != "true" ]]; then
		currentGitPropertyValue=$($GIT_CMD)
		if [[ -n "$currentGitPropertyValue" ]]; then
			return;	
		fi
	fi
	echo "$question"
	read gitPropertyValue
	$GIT_CMD "$gitPropertyValue"
}

changeGitProperty "Entre com seu nome completo" "user.name"
changeGitProperty "Entre com seu e-mail" "user.email"

git config --global push.default simple
# Diff tool meld
git config --global diff.tool meld
# Mantém as credencias em cache por uma hora. Utilizado em https para não ficar pedindo
# usuário e senha a cada requisição.
git config --global credential.helper 'cache --timeout=3600'
# Quebra de linha deve ser a do linux
git config --global core.autocrlf input

if [[ "$CHANGE" == "false" ]]; then
	echo "Configuração realizada com sucesso"
fi