#!/bin/bash -i
# Verifica ambiente
git-init-config

GIT_GLOBAL_NAMESPACE_ID="$1"
NAME="$2"


# Importa chamadas api
. gitlab-call-api.sh

getAttribute() {
	local question="$1"
	echo "$question"
	read "$2"
}

getJSON() {
	local attribute="$1"
	if [[ "$attribute" != "." ]]; then
		attribute=".$attribute"
		noQuotes="true"
	fi
	if [[ -z "$noQuotes" ]]; then
		echo "$JSON_RESP" | jq "$attribute"	
	else
		attibuteValue=$(echo "$JSON_RESP" | jq "$attribute")
		# Substitui " por vazio
		echo $attibuteValue | sed -r 's:"::g'
	fi
}

if [[ -z "$GIT_GLOBAL_NAMESPACE_ID" ]]; then
	gitlab-list-groups " "
	getAttribute "Entre com o id do namespace global" "GIT_GLOBAL_NAMESPACE_ID"
fi

if [[ -z "$NAME" ]]; then
	getAttribute "Entre com o nome do projeto" "NAME"
fi

if [[ -n "$NAME" ]]; then
	JSON_RESP=$(\
	 callGitlabAPI \
	 POST \
	 projects \
	 "{\"name\":\"$NAME\", \"namespace_id\":\"$GIT_GLOBAL_NAMESPACE_ID\"}" \
	 )
	getJSON .
	ID=$(getJSON id)
	if [[ "$ID" != "null" ]]; then
		# Cria branch master e inicializa
		SSH_URL_TO_REPO=$(getJSON ssh_url_to_repo)
		REPO_NAME=$(basename "$SSH_URL_TO_REPO")
		DIR_NAME="${REPO_NAME%.*}"
		git clone "$SSH_URL_TO_REPO"
		cd $DIR_NAME
		touch README.md
		git add README.md
		git commit -m "init"
		echo "Criando branch master"
		git push -v
		cd ..
		rm -Rf $DIR_NAME

		# Cria fork
		echo "Criando fork"
		JSON_RESP=$(callGitlabAPI POST "projects/fork/$ID")
		getJSON .

		ID=$(getJSON id)
		if [[ "$ID" != "null" ]]; then
			SSH_URL_TO_REPO=$(getJSON ssh_url_to_repo)
			JSON_RESP=$(gitlab-list-groups "$GIT_GLOBAL_NAMESPACE_ID")
			GIT_GLOBAL_NAMESPACE=$(getJSON name)
			echo "GIT_GLOBAL_NAMESPACE:$GIT_GLOBAL_NAMESPACE"
			git-clone $SSH_URL_TO_REPO "$GIT_GLOBAL_NAMESPACE" 
		fi
	fi
fi
