#!/bin/bash -i
# Instala golang

# Importação 
. utils.sh

# Necessário o git estar inicializado
git-init-config
# Variáveis 
# Nome deve ser diferente de GOPATH que é global
GOPATH_VAR=~/go

# Instala go
installSoft golang
# Cria o diretório
mkdir $GOPATH
# Adiciona no .bashrc
appendToBashRC "GOPATH" "$GOPATH_VAR" "true" "true"
appendToBashRC "TIDEXA_GLOBAL_SRC_GOPATH" '$GOPATH/src/$TIDEXA_GITLAB_DOMAIN/$TIDEXA_GIT_GLOBAL_NAMESPACE' "true" "true"
appendToBashRC "TIDEXA_GLOBAL_PKG_GOPATH" '$GOPATH/pkg/linux_amd64/$TIDEXA_GITLAB_DOMAIN/$TIDEXA_GIT_GLOBAL_NAMESPACE' "true" "true"
